AskdjangoBasic/askcompany/askcompany/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

def mysum(request, x, y):
    result = x+y
    return HttpResponse('result={}'.format(result))


urlpatterns = [  # 순서가 존재!
    path('admin/', admin.site.urls),
    path('mysum/<int:x>/<int:y>/', mysum),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),

]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

AskdjangoBasic/askcompany/blog/urls.py
from django.urls import path

app_name = 'blog'
urlpatterns = [

]

AskdjangoBasic/askcompany/shop/urls.py
from django.urls import path, register_converter
from .converters import FourDigitYearConverter
from . import views

register_converter(FourDigitYearConverter, 'yyyy')

app_name = 'shop'

urlpatterns = [
    path('archives/<yyyy:year>/', views.archives_year,name='archives_year'),
    path('', views.item_list,name='item_list'),
    path('<int:pk>/', views.item_detail,name='item_detail'),
    # re_path(r'^(?P<pk>\d+)\$',views.item_detail)
    path('new/', views.item_new, name='item_new'),
    path('<int:pk>/edit/',views.item_edit, name='item_edit'), 

]

AskdjangoBasic/askcompany/blog/models.py
from django.db import models
from django.conf import settings
from askcompany.utils import uuid_upload_to

class Post(models.Model):
    # author = models.ForeignKey(
    #    settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    author_name = models.CharField(max_length=20)
    title = models.CharField(max_length=100)
    content = models.TextField()
    photo = models.ImageField(upload_to = uuid_upload_to)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()

AskdjangoBasic/askcompany/common/models.py
from django.db import models

# Create your models here.

AskdjangoBasic/askcompany/shop/models.py
from django.db import models
from django.conf import settings
from askcompany.utils import uuid_upload_to
from django.urls import reverse
# 파일은 FileField, ImageField 많이 사용
# 문자열은 CharField, TextField, SlugField 등
# 날짜/ 시간 :DateTimeField, DateField, TimeField 등
# 이메일 : EmailField

# Relationship Types
# ForeignKey
# ManyToManyField
# OneToOneField

# 옵션
# blank , null , db_index, default,choices, validator


class Item(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField(blank=True)  # 공백도 ok
    price = models.PositiveIntegerField()  # 양수
    photo = models.ImageField(blank = True, upload_to = uuid_upload_to)
    is_publish = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'<{self.pk}> {self.name}'
    
    def get_absolute_url(self):
        return reverse('shop:item_detail',args=[self.pk])
    

# class Post(models.Model):
#     author = models.ForeignKey(
#         settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


"""
from django.conf immport settings
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASECADE)
    title = models.CharField(max_length = 100, db_index = True)
    slug = models.SlugField(allow_unicode= True, db_index= True) # ModelAdmin.prepopulated_fields 편리
    desc = models.TextField(blank = True)
    image = models.ImageField(blank = True)
    is_publish = models.BooleanField(default = False)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now =True)
"""

AskdjangoBasic/askcompany/shop/forms.py
from django import forms
from django.forms import fields
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields = '__all__' 

AskdjangoBasic/askcompany/shop/views.py
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import get_list_or_404, get_object_or_404, render,redirect
from django.http import HttpResponse
from .models import Item
import re
from .forms import  ItemForm 
from django.views.generic import CreateView,UpdateView


def archives_year(request, year):
    return HttpResponse('{}년도에 대한 내용'.format(year))


def view1(request):
    return HttpResponse('HELLO, ASK COMPANY')


def view2(request):
    return render(request, 'template.html')


def view3(request):
    return JsonResponse({'hello': 'Ask company'})


def item_list(request):
    qs = Item.objects.all()

    q = request.GET.get('q', '')

    if q:
        qs.filter(name__icontains=q)

    return render(request, 'shop/item_list.html', {
        'item_list': qs,
        'q': q,
    })


def item_detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return render(request, 'shop/item_detail.html', {
        'item': item
    })

def item_new(request):
    return render(request,'shop/item_form.html')

# def item_new(request, item=None):

#     if request.method == 'POST':
#         form = ItemForm(request.POST, request.FILES,instance=item)
#         if form.is_valid():
#             item = form.save()
#             return redire ct(item)
#     else :
#         form =ItemForm(instance=item)

#     return render(request, 'shop/item_form.html', {
#         'form': form,
#     })

# def item_edit(request, pk):
#     item = get_object_or_404(Item, pk=pk)
#     return item_new(request, item)

item_new = CreateView.as_view(model=Item, form_class=ItemForm)
item_edit = UpdateView.as_view(model=Item,form_class=ItemForm)

AskdjangoBasic/askcompany/askcompany/templates/layout.html
{% load static fresh_static%}
<html>

  <head>
    <meta charset="utf-8"/>
    <title>
      {%block title%}Ask Company{%endblock%}</title>

      <style>
        body {
          background-color: lightpink;
        }
      </style>
      {% block extra_head%}
        <link rel="stylesheet" href="{%fresh_static "main.css" %}"/>
      {% endblock %}
    </head>

    <body>
      <h1>Ask Company</h1>
      {% block content%}{% endblock %}
      <hr/>
      &copy; 2021.07.19. Ask Company
      {% block extra_body %}
        <script src="{%static "main.js" %}"></script>

      {% endblock %}
    </body>

  </html>

AskdjangoBasic/askcompany/blog/templates/blog/layout.html
{% extends "layout.html" %}
{% load fresh_static %}
{% block title %}
Blog by Ask Company
{% endblock%}
{%block extra_head %}
{{ block.super}}
<link rel="stylesheet" href="{% fresh_static " blog/blog.css" %}" />
{% endblock%}
{%block extra_body %}
{{block.super}}
{%end block%}

AskdjangoBasic/askcompany/shop/templates/shop/item_detail.html
{% extends "shop/layout.html" %}
{% load humanize %}

{% block content%}

<h2>
    {{ item.name}}
    {% if item.photo %}
    <br>
    <img src="{{item.photo.url}}" style="max-width: 100%;" />
    <br>
    {% endif%}
    <br>
    가격 :{{item.price|intcomma}}원
    {% if item.desc %}
    <p>
        {{item.desc}}
    </p>
    {% endif %}

</h2>
<hr>
<a href="{% url "shop:item_list" %}">목록</a>
<a href="{% url "shop:item_edit" item.pk %}">수정</a>
{% endblock %}

AskdjangoBasic/askcompany/shop/templates/shop/item_form.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8" />
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
</head>

<body>
    <div class="container">
        <div class="col-sm-12">
            <h2>New Item</h2>

            <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                <table class="table table-bordered">
                {{form.as_table}}
                </table>
                <input type="submit" value="저장하기" class="btn btn-primary" />
            </form>
        </div>
    </div>
</body>

</html>

AskdjangoBasic/askcompany/shop/templates/shop/item_list.html
{% extends "shop/layout.html" %}
{%block content %}
  {{block.super}}
  <!-- 부모내용 같이 써짐 -->
  <form action="" method="GET">
    <input type="text" name="q" value="{{q}}"/>
    <input type="submit" value="search"/>
  </form>
  <ul>
    {% for item in item_list%}
      <li>
        <a href="{{item.get_absolute_url}}">
          {{item.name}}
        </a>
        {{item.price}}
        {{item.desc}}
      </li>
      {% endfor%}
    </ul>

    <hr>
    <a href="{% url "shop:item_new"%}">Item New</a>
    {%endblock%}

AskdjangoBasic/askcompany/shop/templates/shop/layout.html
{% extends "layout.html"%}
{%load fresh_static%}
{% block title %}
  Shop by Ask Company
  {% endblock%}
  {%block extra_head %}
    {{ block.super}}
    <link rel="stylesheet" href="{% fresh_static "shop/shop.css" %}"/>
    {% endblock%}
    {% block extra_body %}
      {{block.super}}
      {%endblock%}