SWIDEA_SITE/config/DevTools/urls.py
from django.urls import path
from . import views
app_name='DevTools'

urlpatterns = [
    path('', views.tool_list, name ='tool_list'),
    path('create/', views.tool_create, name ='tool_create'),
    path('<int:pk>/', views.tool_detail, name ='tool_detail'),
    path('<int:pk>/delete/',views.tool_delete, name='tool_delete'),
    path('<int:pk>/update/', views.tool_update, name='tool_update'),
]

SWIDEA_SITE/config/DevTools/models.py
from django.db import models
from django.shortcuts import reverse
class Tool(models.Model):
    name = models.CharField(max_length=50)
    kind = models.CharField(max_length=50)
    desc = models.TextField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('DevTools:tool_detail', args=[self.pk])

SWIDEA_SITE/config/DevTools/forms.py
from django import forms
from django.forms import fields
from .models import Tool

class ToolForm(forms.ModelForm):
    class Meta:
        model=Tool
        fields = '__all__' 

SWIDEA_SITE/config/DevTools/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView,DetailView,CreateView,UpdateView
from .models import Tool
from .forms import ToolForm
from Ideas.models import Idea

# Create your views here.
tool_list= ListView.as_view(model=Tool,template_name="DevTools/tool_list.html")

tool_create = CreateView.as_view(model=Tool, form_class=ToolForm)

def tool_detail(request,pk):
    tool = Tool.objects.get(pk=pk)
    tool_ideas = Idea.objects.filter(devtool=tool)
    ctx = {"tool": tool, "tool_ideas": tool_ideas}
    return render(request, template_name="DevTools/tool_detail.html", context=ctx)

def tool_delete(request,pk):
    tool = Tool.objects.get(pk=pk)
    tool.delete()
    return redirect('DevTools:tool_list')


tool_update = UpdateView.as_view(model=Tool, form_class=ToolForm,template_name="DevTools/tool_update.html")

SWIDEA_SITE/config/DevTools/templates/DevTools/layout.html
{% extends 'layout.html' %}
{% load static %}
{% block extra_head%}
{{ block.super}}
<link rel="stylesheet" href="{% static "DevTools/tool.css" %}" />
{% endblock  %}
{% block content %}
{% endblock content %}

SWIDEA_SITE/config/DevTools/templates/DevTools/tool_detail.html
{% extends "DevTools/layout.html" %}
{% block content%}
{%load static%}

<div class ="row justify-content-md-center" id="addTool-head">
    <h2>DevTool Detail</h2>
    <span>개발툴 세부내용 페이지입니다. 자신이 다룰수 있는 개발툴에 대한 상세내용을 확인해 보아요.</span>
</div>


<div class="container" id="tool-detail-container">     
    <div class="row" >
        <span id="tool-name">{{tool.name}} </span>
    </div>
    <div class="row" id="tool_list_row">
        <span>{{tool.kind}}<br>
        {{tool.desc}}</span> 
    </div>
    <div class="row" id="tool_list_row">
        <hr id="tool-detail-hr">
        <span id="pos-sw"> > 만들 수 있는 SW 목록 </span>
    </div>
    <div class="row" id="tool_list_row">
        <span sytle="margin-top:10px;">
        {% for idea in tool_ideas%}
            <a id="tool-idea" href="{% url "Ideas:idea_detail" idea.pk%}">{{idea.title}}</a>
            <br>
        {%endfor%}
        </span>
    </div>
</div>
    <div class="row" id="btn-row">
        <a id="btn-del" onclick="return confirm('정말 삭제하시겠습니까?');" href="{% url 'DevTools:tool_delete' tool.pk%}" class="btn btn-lg active" role="button" aria-pressed="true">삭제</a>
        <a id="btn-list" href="{% url 'DevTools:tool_list' %}" class="btn btn-lg active" role="button" aria-pressed="true">목록</a>
        <a id="btn-update" href="{% url 'DevTools:tool_update' tool.pk %}" class="btn btn-lg active" role="button" aria-pressed="true">수정</a> 
    </div>
{% endblock %}

SWIDEA_SITE/config/DevTools/templates/DevTools/tool_form.html
{% extends "DevTools/layout.html" %}
{%load static%}
{% block content %}
{{block.super}}
<div class="container">
            <div class ="row justify-content-md-center" id="addTool-head">
                <h2>DevTool Register</h2>
                <span>개발툴 등록 페이지입니다. 자신이 다룰 수 있는 개발툴을 등록해보세요.</span>
            </div>
            <div class ="row justify-content-md-center">
            </div>     
            <div class="row justify-content-md-center" id="form-container">
                <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="submit" class="btn rounded" id="submit-btn" />
                </form>
            </div>
</div>
{% endblock %}

SWIDEA_SITE/config/DevTools/templates/DevTools/tool_list.html
<!DOCTYPE html>
{% extends 'DevTools/layout.html' %}

{% block content %}
{{block.super}}
<div class ="row justify-content-md-center" id="addTool-head">
    <h2>Tool List</h2>
    <span>개발툴 목록 페이지 입니다. 자신이 사용가능한 개발툴의 목록을 확인해보세요</span>
</div>


<div class="container rounded" id="container_tool">
    <div class="row justify-content-md-center">
        <div class="col col-sm-11" id="tool_list">
        {% for tool in object_list  %}
    
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"><a href="{{tool.get_absolute_url}}">{{tool.name}}</a></h5>
                <hr id="tool-hr">
                <p class="card-text">
                <span id ="tool-kind">{{tool.kind}}</span>
                </p>
                <span>{{tool.desc}}</span><br>
            </div>
        </div>
        
        {% endfor %}
        </div>
    </div>
        
</div>


{% endblock%}
</div>

SWIDEA_SITE/config/DevTools/templates/DevTools/tool_update.html
{% extends "DevTools/layout.html" %}
{%load static%}
{% block content %}
{{block.super}}
<div class="container">
            <div class="row justify-content-md-center" id="addTool-head">
                    <h2>DevTool Detail Update</h2>
                    <span style="color:white">개발툴 세부내용 수정 페이지입니다. 개발툴에 대해 수정사항이 있으면 고쳐보아요.</span>
            </div>      
            <div class="row justify-content-md-center" id="form-container">
                <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="submit" class="btn rounded" id="submit-btn" />
                </form>
            </div>
</div>
{% endblock %}