SWIDEA_SITE/config/Ideas/urls.py
from django.urls import path
from . import views

app_name ='Ideas'

urlpatterns = [
    path('', views.idea_list, name='idea_list'),
    path('create/', views.idea_create, name ='idea_create'),
    path('<int:pk>/', views.idea_detail, name ='idea_detail'),
    path('<int:pk>/delete/',views.idea_delete, name='idea_delete'),
    path('<int:pk>/update/', views.idea_update, name='idea_update'),
    path('interest_add/', views.interest_add, name="interest_add"),
    path('interest_minus/', views.interest_minus, name="interest_minus"),
    
]

SWIDEA_SITE/config/Ideas/models.py
from django.db import models
from django.shortcuts import reverse


class Idea(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to = "idea_image/%Y/%m/%d/",null=True,blank = True)  
    desc = models.TextField()
    interest = models.PositiveIntegerField(default =0)
    devtool = models.ForeignKey(
        "DevTools.Tool", on_delete=models.CASCADE, related_name="ideas"
    )

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('Ideas:idea_detail', args=[self.pk])

SWIDEA_SITE/config/Ideas/forms.py
from django import forms
from django.forms import fields
from .models import Idea

class IdeaForm(forms.ModelForm):
    class Meta:
        model=Idea
        fields = '__all__' 

SWIDEA_SITE/config/Ideas/views.py
from typing import List
from django.db import models
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import ListView,DetailView
from .models import Idea
from .forms import  IdeaForm 
from django.views.generic import CreateView,UpdateView
from django.http import HttpResponse,JsonResponse
import json

idea_list = ListView.as_view(model=Idea)

def idea_create(request):
    return render(request,'Ideas/idea_form.html')

idea_create = CreateView.as_view(model=Idea, form_class=IdeaForm)

def idea_detail(request,pk):
    idea = Idea.objects.get(pk=pk)
    ctx = {"idea": idea}
    return render(request, template_name="Ideas/idea_detail.html", context=ctx)

def idea_delete(request,pk):
    idea = Idea.objects.get(pk=pk)
    idea.delete()
    return redirect('Ideas:idea_list')


idea_update = UpdateView.as_view(model=Idea, form_class=IdeaForm,template_name="Ideas/idea_update.html")

def interest_add(request):
    if request.is_ajax():
        idea_pk= request.GET['pk']
        idea = Idea.objects.get(pk=idea_pk)
        idea.interest= idea.interest+1
        idea.save()
        context ={'interest': idea.interest}
    return HttpResponse(json.dumps(context), content_type='application/json')

def interest_minus(request):
    if request.is_ajax():
        idea_pk= request.GET['pk']
        idea = Idea.objects.get(pk=idea_pk)
        idea.interest= idea.interest-1
        idea.save()
        context ={'interest': idea.interest}
    return HttpResponse(json.dumps(context), content_type='application/json')

SWIDEA_SITE/config/Ideas/templates/Ideas/idea_detail.html
{% extends "Ideas/layout.html" %}
{% block content%}
{%load static%}
<div class="container">
    <div class="row justify-content-md-center" id="addItem-head">
        <h2>Idea Detail</h2>
        <span style="color:white">아이디어 세부내용 페이지 입니다. 당신이 구현하려 한 아이디어들을 자세히 살펴보세요.</span>
    </div>      
    <div class ="row justify-content-md-center">
        <div class="container" id="detail-container">
            <div class=row>
                <div class="col">
                    {% if idea.image %}
                        <img src="{{idea.image.url}}" style="max-width: 100%;" />
                    {%else%}
                        <img src="{% static "Ideas/no_image.jpg" %}" class="card-img-top" alt="...">
                    {% endif %}
                </div>
                <div class="col">
                    <span id="detail-item-title">{{idea.title}}</span>
                    <br><br>
                    <span id="detail">1) 아이디어 관심도 : <br>
                    {{idea.interest}}</span> <br><br>
                    <span id="detail"> 2) 예상 개발 툴 : <br>
                    <a id="idea-tool" href="{% url "DevTools:tool_detail" idea.devtool.pk %}">
                    {{idea.devtool}}</a></span><br><br>
                    <span id="detail"> 3) 아이디어 설명 : <br>
                    {{idea.desc}} </span> <br>
                </div>
            </div>
            <div class="row" id="btn-row">
                <a id="btn-del" onclick="return confirm('정말 삭제하시겠습니까?');" href="{% url 'Ideas:idea_delete' idea.pk%}" class="btn btn-lg active" role="button" aria-pressed="true">삭제</a>
                <a id="btn-list" href="{% url 'Ideas:idea_list' %}" class="btn btn-lg active" role="button" aria-pressed="true">목록</a>
                <a id="btn-update" href="{% url 'Ideas:idea_update' idea.pk %}" class="btn btn-lg active" role="button" aria-pressed="true">수정</a>
            </div>
        </div>
    <div>
</div>
{% endblock %}

SWIDEA_SITE/config/Ideas/templates/Ideas/idea_form.html
{% extends "Ideas/layout.html" %}
{%load static%}
{% block content %}
{{block.super}}
<div class="container">
            <div class="row justify-content-md-center" id="addItem-head">
                    <h2>Idea Register</h2>
                    <span style="color:white">아이디어 등록 페이지입니다. 당신의 아이디어를 잊지 말고 기록하세요!</span>
            </div>      
            <div class="row justify-content-md-center" id="form-container">
                <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="submit" class="btn rounded" id="submit-btn" />
                </form>
            </div>
</div>
{% endblock %}

SWIDEA_SITE/config/Ideas/templates/Ideas/idea_list.html
<!DOCTYPE html>
{% extends 'ideas/layout.html' %}
{%load static%}
{% block content %}
{{block.super}}
<div class="row justify-content-md-center" id="addItem-head">
        <h2>Idea List</h2>
        <span style="color:white">나의 아이디어를 잊지 말고 기록해보세요</span>
</div> 
<div class="container rounded" id="container_idea">
{% for idea in idea_list  %}
    <div class="card" id ="item">
        {% if idea.image%}
            <img src="{{idea.image.url}}" class="card-img-top" alt="...">
        {%else%}
        <img src="{% static "Ideas/no_image.jpg" %}" class="card-img-top" alt="...">
        {% endif %}
        <div class="card-body">
            <p class="card-text">
                <a href="{% url 'Ideas:idea_detail' idea.pk %}"> 
            {{idea.title}}
            </a>
            <hr id="card-line">
            <span>예상 개발 툴 :  {{idea.devtool}}</span>
            <br>
            <span>아이디어 관심도 : <span id="interest{{idea.pk}}">{{idea.interest}}</span>
            <button id="increase" onclick="addInterest({{idea.pk}})">+</button>
            <button id="decrease" onclick="minusInterest({{idea.pk}})">-</button>
            </p>
        </div>
        
    </div>

{% endfor %}

{% endblock%}
{% block extra_body %}
    <script type="text/javascript">
        function addInterest(pk){
            $.ajax({
                url: "{% url 'Ideas:interest_add' %}",
                data:{
                    'pk':pk,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                dataType:"json",
                success: function(response) {
                    $('#interest'+pk).html(response.interest)
                }
            });
        };

        function minusInterest(pk){
            $.ajax({
                url: "{% url 'Ideas:interest_minus' %}",
                data:{
                    'pk':pk
                },
                dataType:"json",
                success: function(response) {
                    $('#interest'+pk).html(response.interest)
                    console.log($('#interest'))
                }
            });
        };

    </script>
{% endblock %}
</div>

SWIDEA_SITE/config/Ideas/templates/Ideas/idea_update.html
{% extends "Ideas/layout.html" %}
{%load static%}
{% block content %}
{{block.super}}
<div class="container">
            <div class="row justify-content-md-center" id="addItem-head">
                    <h2>Idea Update</h2>
                    <span style="color:white">아이디어 세부내용 수정 페이지 입니다. 아이디어를 구체화하거나 내용을 변경해 보아요!</span>
            </div>      
            <div class="row justify-content-md-center" id="form-container">
                <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="submit" class="btn rounded" id="submit-btn" />
                </form>
            </div>
</div>
{% endblock %}

SWIDEA_SITE/config/Ideas/templates/Ideas/layout.html
{% extends 'layout.html' %}
{% load static %}
{% block extra_head%}
{{ block.super}}
<link rel="stylesheet" href="{% static "Ideas/Ideas.css" %}" />
{% endblock  %}
{% block content %}
{% endblock content %}